name: Continuous Delivery
# This workflow is triggered on pushes to master
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Create patch version on push to master
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create release tag
        run: echo ::set-env name=RELEASE_TYPE::${GITHUB_REF#refs/*/}
      - name: Build, tag, and push build to Amazon S3
        run: |
          RELEASE_TYPE=minor
          git tag ${RELEASE_TYPE}
          git push origin ${RELEASE_TYPE}
          git tag --delete ${RELEASE_TYPE}
          git push --delete origin ${RELEASE_TYPE}
